export const actionIds = {
  SETUP_SESSION_INFO: '[1] Store nickname and room name.',
  ENROLL_ROOM_REQUEST: '[2] Send a request to the server informing nickname and room to enroll',
  DISCONNECT: '[3] User wants to disconnect',
  ON_DISCONNECT: '[4] Server notifies disconnection',
  MESSAGE_RECEIVED: '[5] Chat message received from socket',
  MESSAGE_LIST_RECEIVED: '[6] Chat message list received from socket',
  SEND_MESSAGE:'[7] Send message to the server',
  UPDATE_CURRENT_MESSAGE:'[8] Update current message in store',
  UPDATE_SEARCH_TERM:'[9] Update search term in store',
  UPDATE_ROOM_LIST:'[10] Update list of available rooms from API',
  UPDATE_ROOM_LIST_SUCCESS:'[11] List of available rooms updated succesfully',
  UPDATE_ROOM_LIST_FAIL:'[12] List of available rooms update failed',
  UPDATE_CANDIDATE_ROOM:'[13] Update candidate room in store',
  UPDATE_CANDIDATE_NICKNAME:'[14] Update candidate nickname in store',
};
